export default [
  {
    id: "1000",
    name: "Tester SSr (Caja negra)",
    description: "La empresa desarrolla inteligencia artificial orientada a los negocios financieros. Es un excelente lugar donde crecer mientras te capacitas en las últimas tecnologías. Gran ambiente de trabajo, colaborativo y sin competencia.",
    exclusive_requirements: [
      "Contar con 3 años como mínimo de experiencia laboral previa en posiciones similares.",
      "Haber trabajado con tecnologías web al menos 2 años.",
      "Conocimientos de SQL",
      "Experiencia en testing funcional de caja negra.",
      "Experiencia en reporte de defectos y ejecución de casos de prueba.",
      "Experiencia en diseño de casos de prueba.",
      "Experiencia en análisis de requerimientos.",
    ],
    desirable_requirements: [
      "Haber trabajado en ambientes dinámicos.",
      "Experiencia en testing de caja blanca.",
      "Experiencia en automatización de pruebas.",
      "Experiencia en pruebas de rendimientos y concurrencia.",
      "Experiencia en web services.",
      "Experiencia en metodologías ágiles.",
      "Experiencia en procesos batch.",
      "Experiencias en aplicaciones de escritorio.",
      "Conocimientos del negocio bancario.",
      "Experiencia de stored procedures.",
      "Haber utilizado herramientas de Test Management.",
    ],
    benefits: [
      "Plan de carrera",
      "Clases de inglés in company",
      "OSDE210",
      "Home Office",
      "Trabajo colaborativo",
      "Vacaciones flexibles",
      "Eventos corporativos",
      "Horarios flexibles",
      "Membresía a centro deportivo a cargo de la empresa",
      "Programa de referidos",
      "Ajustes salariales cada 6 meses según inflación y desempeño",
      "Descuentos en Educación IT y el CUI",
      "Dia libre por cumpleaños",
      "Espacios recreativos",
      "Convenios con marcas",
    ],
    experience: "3-5 años de experiencia",
    kindPosition: "Full Time",
    location: "Congreso, Buenos Aires",
    featured: false,
    category: "QA",
    mode: "Remoto/On Site",
    contract: "Relación de dependencia",
    consultant: "BudaIT"
  },
  {
    id: "",
    name: "Tester SSr (Caja negra)",
    description: "La empresa desarrolla inteligencia artificial orientada a los negocios financieros. Es un excelente lugar donde crecer mientras te capacitas en las últimas tecnologías. Gran ambiente de trabajo, colaborativo y sin competencia.",
    exclusive_requirements: [
      "Contar con 3 años como mínimo de experiencia laboral previa en posiciones similares.",
      "Haber trabajado con tecnologías web al menos 2 años.",
      "Conocimientos de SQL",
      "Experiencia en testing funcional de caja negra.",
      "Experiencia en reporte de defectos y ejecución de casos de prueba.",
      "Experiencia en diseño de casos de prueba.",
      "Experiencia en análisis de requerimientos.",
    ],
    desirable_requirements: [
      "Haber trabajado en ambientes dinámicos.",
      "Experiencia en testing de caja blanca.",
      "Experiencia en automatización de pruebas.",
      "Experiencia en pruebas de rendimientos y concurrencia.",
      "Experiencia en web services.",
      "Experiencia en metodologías ágiles.",
      "Experiencia en procesos batch.",
      "Experiencias en aplicaciones de escritorio.",
      "Conocimientos del negocio bancario.",
      "Experiencia de stored procedures.",
      "Haber utilizado herramientas de Test Management.",
    ],
    benefits: [
      "Plan de carrera",
      "Clases de inglés in company",
      "OSDE210",
      "Home Office",
      "Trabajo colaborativo",
      "Vacaciones flexibles",
      "Eventos corporativos",
      "Horarios flexibles",
      "Membresía a centro deportivo a cargo de la empresa",
      "Programa de referidos",
      "Ajustes salariales cada 6 meses según inflación y desempeño",
      "Descuentos en Educación IT y el CUI",
      "Dia libre por cumpleaños",
      "Espacios recreativos",
      "Convenios con marcas",
    ],
    experience: "3-5 años de experiencia",
    kindPosition: "Full Time",
    location: "Congreso, Buenos Aires",
    featured: true,
    category: "QA",
    mode: "Remoto",
    contract: "Freelance",
    consultant: "BudaIT"
  },
  {
    id: "",
    name: "Tester SSr (Caja negra)",
    description: "La empresa desarrolla inteligencia artificial orientada a los negocios financieros. Es un excelente lugar donde crecer mientras te capacitas en las últimas tecnologías. Gran ambiente de trabajo, colaborativo y sin competencia.",
    exclusive_requirements: [
      "Contar con 3 años como mínimo de experiencia laboral previa en posiciones similares.",
      "Haber trabajado con tecnologías web al menos 2 años.",
      "Conocimientos de SQL",
      "Experiencia en testing funcional de caja negra.",
      "Experiencia en reporte de defectos y ejecución de casos de prueba.",
      "Experiencia en diseño de casos de prueba.",
      "Experiencia en análisis de requerimientos.",
    ],
    desirable_requirements: [
      "Haber trabajado en ambientes dinámicos.",
      "Experiencia en testing de caja blanca.",
      "Experiencia en automatización de pruebas.",
      "Experiencia en pruebas de rendimientos y concurrencia.",
      "Experiencia en web services.",
      "Experiencia en metodologías ágiles.",
      "Experiencia en procesos batch.",
      "Experiencias en aplicaciones de escritorio.",
      "Conocimientos del negocio bancario.",
      "Experiencia de stored procedures.",
      "Haber utilizado herramientas de Test Management.",
    ],
    benefits: [
      "Plan de carrera",
      "Clases de inglés in company",
      "OSDE210",
      "Home Office",
      "Trabajo colaborativo",
      "Vacaciones flexibles",
      "Eventos corporativos",
      "Horarios flexibles",
      "Membresía a centro deportivo a cargo de la empresa",
      "Programa de referidos",
      "Ajustes salariales cada 6 meses según inflación y desempeño",
      "Descuentos en Educación IT y el CUI",
      "Dia libre por cumpleaños",
      "Espacios recreativos",
      "Convenios con marcas",
    ],
    experience: "3-5 años de experiencia",
    kindPosition: "Full Time",
    location: "Congreso, Buenos Aires",
    featured: false,
    category: "QA",
    mode: "Remoto",
    contract: "Freelance",
    consultant: "BudaIT"
  },
  {
    id: "",
    name: "Tester SSr (Caja negra)",
    description: "La empresa desarrolla inteligencia artificial orientada a los negocios financieros. Es un excelente lugar donde crecer mientras te capacitas en las últimas tecnologías. Gran ambiente de trabajo, colaborativo y sin competencia.",
    exclusive_requirements: [
      "Contar con 3 años como mínimo de experiencia laboral previa en posiciones similares.",
      "Haber trabajado con tecnologías web al menos 2 años.",
      "Conocimientos de SQL",
      "Experiencia en testing funcional de caja negra.",
      "Experiencia en reporte de defectos y ejecución de casos de prueba.",
      "Experiencia en diseño de casos de prueba.",
      "Experiencia en análisis de requerimientos.",
    ],
    desirable_requirements: [
      "Haber trabajado en ambientes dinámicos.",
      "Experiencia en testing de caja blanca.",
      "Experiencia en automatización de pruebas.",
      "Experiencia en pruebas de rendimientos y concurrencia.",
      "Experiencia en web services.",
      "Experiencia en metodologías ágiles.",
      "Experiencia en procesos batch.",
      "Experiencias en aplicaciones de escritorio.",
      "Conocimientos del negocio bancario.",
      "Experiencia de stored procedures.",
      "Haber utilizado herramientas de Test Management.",
    ],
    benefits: [
      "Plan de carrera",
      "Clases de inglés in company",
      "OSDE210",
      "Home Office",
      "Trabajo colaborativo",
      "Vacaciones flexibles",
      "Eventos corporativos",
      "Horarios flexibles",
      "Membresía a centro deportivo a cargo de la empresa",
      "Programa de referidos",
      "Ajustes salariales cada 6 meses según inflación y desempeño",
      "Descuentos en Educación IT y el CUI",
      "Dia libre por cumpleaños",
      "Espacios recreativos",
      "Convenios con marcas",
    ],
    experience: "3-5 años de experiencia",
    kindPosition: "Full Time",
    location: "Congreso, Buenos Aires",
    featured: true,
    category: "QA",
    mode: "On site",
    contract: "Freelance",
    consultant: "BudaIT"
  }
]
